name: 'sql_sf_migrate'
version: '1.0.0'
config-version: 2

profile: 'sql_sf_migrate'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  sql_sf_migrate:
    +materialized: table